language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - pip install coveralls flake8
  - coverage run --source=flask_utils setup.py test

script:
  - flake8 .
  - make test

before_deploy:
  - git describe --dirty --always > VERSION

deploy:
  provider: pypi
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on: 
    tags: true